### ISSUE TITLE
Using the new plugins{} declaration causes exception

### ISSUE THREAD

**Issue by athkalia** [hauner/gradle-plugins#1]
Hello,

your plugin causes the following error in my build when I use the new plugins{} declaration:

```
* What went wrong:
An exception occurred applying plugin request [id: 'com.github.hauner.jarTest', version: '1.0']
> Failed to apply plugin [id 'com.github.hauner.jarTest']
   > Could not find property 'testClasses' on project ':common'.
```

If I use the old plugin style

```
apply plugin: "com.github.hauner.jarTest"
```

everything works just fine.

**Comment by hauner** [comment]
Ok, this was a bit tricky to reproduce :)

When i move the `apply plugin "groovy"` from the top level projects `subprojects` block to the project that uses the `jarTest` plugin i receive the same error. My `build.gradle` now looks like this:

```
plugins {
  id "com.github.hauner.jarTest" version "1.0"
}

apply plugin: 'groovy'
```

I guess the problem is that gradle applies the `jarTest` plugin before it applies the `groovy` plugin. Which is bad because jarTest depends on the `testClasses` task that is not there yet...

Interesting is that gradle does not allow to move the `apply` to the top.

I will check if there is a way to handle this. Thanks for reporting.

**Comment by athkalia** [comment]
No bother, I'll bother you if  I find anything else during my migration from maven to gradle : >
