### ISSUE TITLE
Plugin built for Java 8?

### ISSUE THREAD

**Issue by pbouillet** [hauner/gradle-plugins#3]
I wanted to try out this plugin, but apparently it seems like it only runs with Java 8 or higher. Could you change it to at least 7 (I guess 6 would be possible too).

**Comment by hauner** [comment]
did you try 1.0.1? That version is built with Java 6 compatibility.

https://plugins.gradle.org/plugin/com.github.hauner.jarTest/1.0.1

**Comment by pbouillet** [comment]
Pretty sure I did. I just copied the snippet from the gradle plugin site into our application and then it complained about unsupported major minor version 52.0 (which is java 8).

**Comment by grubers** [comment]
The link at the bottom of the page [https://github.com/hauner/gradle-plugins/tree/master/jartest](https://github.com/hauner/gradle-plugins/tree/master/jartest) to `plugins.gradle.org` simply points to [https://plugins.gradle.org/plugin/com.github.hauner.jarTest/1.0](https://plugins.gradle.org/plugin/com.github.hauner.jarTest/1.0) instead of to the newer version [https://plugins.gradle.org/plugin/com.github.hauner.jarTest/1.0.1](https://plugins.gradle.org/plugin/com.github.hauner.jarTest/1.0.1). There the snippet is correct (matches the newer version) and works with a Java version < 8 (and >= 6).

**Comment by hauner** [comment]
Thanks for noticing, I have fixed the link. :-)
